apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: k-s-demo-app--
build:
  artifacts:
  - image: registry.cn-shanghai.aliyuncs.com/zb-test/demo
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base-platform-api-0.3
      dependencies:
        paths:
        - src
        - pom.xml
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
